services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: brasilia
      POSTGRES_PASSWORD: brasilia
      POSTGRES_DB: brb_ticketing
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brasilia -d brb_ticketing"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    volumes:
      - kafka-data:/apache/kafka
    networks:
      - local-network
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8084:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: ticketing-local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9090
    networks:
      - local-network
networks:
  local-network:
    driver: bridge
volumes:
  kafka-data:
